language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: UPDATE THIS
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
  - bash travis-after-build.sh
